export const enum OrderStates {
    PAYMENT_PENDING = 'PAYMENT_PENDING',
    PAYMENT_CONFIRM = 'PAYMENT_CONFIRM',
    CONFIRM = 'CONFIRM',
    SHIPMENT = 'SHIPMENT',
    SUCCESS = 'SUCCESS',
    CANCEL = 'CANCEL',
    REFUND = 'REFUND',
}
